/* This file was generated by syncqt. */
#ifndef QT_QTHTTPSERVER_VERSION_H
#define QT_QTHTTPSERVER_VERSION_H

#define QTHTTPSERVER_VERSION_STR "6.7.3"

#define QTHTTPSERVER_VERSION 0x060703

#endif // QT_QTHTTPSERVER_VERSION_H
