/* This file was generated by syncqt. */
#ifndef QT_QTCHARTSQML_VERSION_H
#define QT_QTCHARTSQML_VERSION_H

#define QTCHARTSQML_VERSION_STR "6.7.3"

#define QTCHARTSQML_VERSION 0x060703

#endif // QT_QTCHARTSQML_VERSION_H
