/* This file was generated by syncqt. */
#ifndef QT_QTCOAP_VERSION_H
#define QT_QTCOAP_VERSION_H

#define QTCOAP_VERSION_STR "6.7.3"

#define QTCOAP_VERSION 0x060703

#endif // QT_QTCOAP_VERSION_H
