/* This file was generated by syncqt. */
#ifndef QT_QTSERIALBUS_VERSION_H
#define QT_QTSERIALBUS_VERSION_H

#define QTSERIALBUS_VERSION_STR "6.7.3"

#define QTSERIALBUS_VERSION 0x060703

#endif // QT_QTSERIALBUS_VERSION_H
