/* This file was generated by syncqt. */
#ifndef QT_QTGRPC_VERSION_H
#define QT_QTGRPC_VERSION_H

#define QTGRPC_VERSION_STR "6.7.3"

#define QTGRPC_VERSION 0x060703

#endif // QT_QTGRPC_VERSION_H
