/* This file was generated by syncqt. */
#ifndef QT_QTMQTT_VERSION_H
#define QT_QTMQTT_VERSION_H

#define QTMQTT_VERSION_STR "6.7.3"

#define QTMQTT_VERSION 0x060703

#endif // QT_QTMQTT_VERSION_H
